"""Phase-2 building-block GPU kernels + verification gate (ARCHITECTURE.md §3,§6).

Hand-written Mojo Metal kernels for the ops the Qwen2 forward pass is built from,
each verified against a NumPy reference (cross-checked vs HF, see capture.py):

  - rmsnorm_kernel   RMSNorm (one thread per row)
  - matmul_kernel    y = x @ W.T (+ bias)  (one thread per output element)
  - silu_mul_kernel  silu(a) * b elementwise

The SwiGLU MLP is composed on the host from matmul + silu_mul + matmul, exactly
as a decoder layer will drive them. Fixtures live in tests/fixtures/kernels/;
`syn_*` are committed, `real_*` are regenerated by `pixi run kernels-capture`.
Any mismatch → non-zero exit, so `pixi run kernels-spike` is a real gate.
"""

from std.math import sqrt, exp, ceildiv
from std.sys import has_accelerator
from std.gpu import global_idx
from std.gpu.host import DeviceContext, DeviceBuffer
from std.os.path import exists
from layout import TileTensor, TensorLayout, row_major

comptime EPS = Float32(1.0e-6)
comptime TOL = Float32(3.0e-3)
comptime BLOCK = 256


def rmsnorm_kernel[
    LT: TensorLayout
](
    X: TileTensor[DType.float32, LT, MutAnyOrigin],
    W: TileTensor[DType.float32, LT, MutAnyOrigin],
    Y: TileTensor[DType.float32, LT, MutAnyOrigin],
    T: Int,
    H: Int,
):
    comptime assert X.flat_rank == 1
    var t = global_idx.x
    if t >= T:
        return
    var ss = Float32(0.0)
    for d in range(H):
        var v = rebind[Scalar[DType.float32]](X[t * H + d])
        ss += v * v
    var rms = sqrt(ss / Float32(H) + EPS)
    for d in range(H):
        var v = rebind[Scalar[DType.float32]](X[t * H + d])
        var wv = rebind[Scalar[DType.float32]](W[d])
        Y[t * H + d] = rebind[Y.ElementType](v / rms * wv)


def matmul_kernel[
    LT: TensorLayout
](
    X: TileTensor[DType.float32, LT, MutAnyOrigin],
    W: TileTensor[DType.float32, LT, MutAnyOrigin],
    B: TileTensor[DType.float32, LT, MutAnyOrigin],
    Y: TileTensor[DType.float32, LT, MutAnyOrigin],
    M: Int,
    K: Int,
    N: Int,
    use_bias: Int,
):
    comptime assert X.flat_rank == 1
    var idx = global_idx.x
    if idx >= M * N:
        return
    var m = idx // N
    var n = idx % N
    var acc = Float32(0.0)
    for k in range(K):
        var xv = rebind[Scalar[DType.float32]](X[m * K + k])
        var wv = rebind[Scalar[DType.float32]](W[n * K + k])
        acc += xv * wv
    if use_bias != 0:
        acc += rebind[Scalar[DType.float32]](B[n])
    Y[m * N + n] = rebind[Y.ElementType](acc)


def silu_mul_kernel[
    LT: TensorLayout
](
    A: TileTensor[DType.float32, LT, MutAnyOrigin],
    B: TileTensor[DType.float32, LT, MutAnyOrigin],
    Y: TileTensor[DType.float32, LT, MutAnyOrigin],
    n: Int,
):
    comptime assert A.flat_rank == 1
    var i = global_idx.x
    if i >= n:
        return
    var a = rebind[Scalar[DType.float32]](A[i])
    var b = rebind[Scalar[DType.float32]](B[i])
    var s = a / (1.0 + exp(-a))
    Y[i] = rebind[Y.ElementType](s * b)


# ── host helpers ──────────────────────────────────────────────────────────────


def read_f32_file(path: String) raises -> List[Float32]:
    var out = List[Float32]()
    with open(path, "r") as f:
        var raw = f.read_bytes()
        var n = len(raw) // 4
        var p = raw.unsafe_ptr().bitcast[Float32]()
        for i in range(n):
            out.append(p[i])
    return out^


def read_ints(path: String) raises -> List[Int]:
    var out = List[Int]()
    with open(path, "r") as f:
        var s = f.read()
        for part in s.split(" "):
            var q = String(part).strip()
            if q.byte_length() > 0:
                out.append(Int(atol(q)))
    return out^


def make_buf(ctx: DeviceContext, host: List[Float32]) raises -> DeviceBuffer[DType.float32]:
    var n = len(host)
    var dev = ctx.enqueue_create_buffer[DType.float32](n)
    with dev.map_to_host() as m:
        var mt = TileTensor(m, row_major(n))
        comptime assert mt.flat_rank == 1
        for i in range(n):
            mt[i] = rebind[mt.ElementType](host[i])
    return dev^


def max_abs_vs(dev: DeviceBuffer[DType.float32], expected: List[Float32]) raises -> Float32:
    var n = len(expected)
    var worst = Float32(0.0)
    with dev.map_to_host() as m:
        var mt = TileTensor(m, row_major(n))
        comptime assert mt.flat_rank == 1
        for i in range(n):
            var got = rebind[Scalar[DType.float32]](mt[i])
            var diff = abs(got - expected[i])
            if diff > worst:
                worst = diff
    return worst


def report(name: String, max_abs: Float32) -> Bool:
    var ok = max_abs < TOL
    var tag = "OK" if ok else "FAIL"
    print("  ", name, " max_abs=", max_abs, " [", tag, "]", sep="")
    return ok


# ── per-kernel runners ────────────────────────────────────────────────────────


def run_rmsnorm(ctx: DeviceContext, dir: String) raises -> Bool:
    var meta = read_ints(dir + "/meta.txt")
    var T = meta[0]
    var H = meta[1]
    var x = read_f32_file(dir + "/x.bin")
    var w = read_f32_file(dir + "/w.bin")
    var expected = read_f32_file(dir + "/expected.bin")

    var x_dev = make_buf(ctx, x)
    var w_dev = make_buf(ctx, w)
    var y_dev = ctx.enqueue_create_buffer[DType.float32](T * H)

    var lay = row_major(T * H)
    comptime k = rmsnorm_kernel[type_of(lay)]
    ctx.enqueue_function[k](
        TileTensor(x_dev, row_major(len(x))),
        TileTensor(w_dev, row_major(len(w))),
        TileTensor(y_dev, lay),
        T, H,
        grid_dim=ceildiv(T, 64),
        block_dim=64,
    )
    ctx.synchronize()
    return report(dir, max_abs_vs(y_dev, expected))


def run_matmul(ctx: DeviceContext, dir: String) raises -> Bool:
    var meta = read_ints(dir + "/meta.txt")
    var M = meta[0]
    var K = meta[1]
    var N = meta[2]
    var use_bias = meta[3]
    var x = read_f32_file(dir + "/x.bin")
    var W = read_f32_file(dir + "/W.bin")
    var b = read_f32_file(dir + "/b.bin")
    var expected = read_f32_file(dir + "/expected.bin")

    var x_dev = make_buf(ctx, x)
    var w_dev = make_buf(ctx, W)
    var b_dev = make_buf(ctx, b)
    var y_dev = ctx.enqueue_create_buffer[DType.float32](M * N)

    var lay = row_major(M * N)
    comptime k = matmul_kernel[type_of(lay)]
    ctx.enqueue_function[k](
        TileTensor(x_dev, row_major(len(x))),
        TileTensor(w_dev, row_major(len(W))),
        TileTensor(b_dev, row_major(len(b))),
        TileTensor(y_dev, lay),
        M, K, N, use_bias,
        grid_dim=ceildiv(M * N, BLOCK),
        block_dim=BLOCK,
    )
    ctx.synchronize()
    return report(dir, max_abs_vs(y_dev, expected))


def matmul(
    ctx: DeviceContext,
    mut x_dev: DeviceBuffer[DType.float32],
    mut w_dev: DeviceBuffer[DType.float32],
    M: Int, K: Int, N: Int,
) raises -> DeviceBuffer[DType.float32]:
    var y_dev = ctx.enqueue_create_buffer[DType.float32](M * N)
    var b_dev = ctx.enqueue_create_buffer[DType.float32](N)
    b_dev.enqueue_fill(0.0)
    var lay = row_major(M * N)
    comptime k = matmul_kernel[type_of(lay)]
    ctx.enqueue_function[k](
        TileTensor(x_dev, row_major(M * K)),
        TileTensor(w_dev, row_major(N * K)),
        TileTensor(b_dev, row_major(N)),
        TileTensor(y_dev, lay),
        M, K, N, 0,
        grid_dim=ceildiv(M * N, BLOCK),
        block_dim=BLOCK,
    )
    return y_dev^


def run_swiglu(ctx: DeviceContext, dir: String) raises -> Bool:
    var meta = read_ints(dir + "/meta.txt")
    var T = meta[0]
    var H = meta[1]
    var I = meta[2]
    var x = read_f32_file(dir + "/x.bin")
    var wg = read_f32_file(dir + "/w_gate.bin")
    var wu = read_f32_file(dir + "/w_up.bin")
    var wd = read_f32_file(dir + "/w_down.bin")
    var expected = read_f32_file(dir + "/expected.bin")

    var x_dev = make_buf(ctx, x)
    var wg_dev = make_buf(ctx, wg)
    var wu_dev = make_buf(ctx, wu)
    var wd_dev = make_buf(ctx, wd)

    var g_dev = matmul(ctx, x_dev, wg_dev, T, H, I)   # [T, I]
    var u_dev = matmul(ctx, x_dev, wu_dev, T, H, I)   # [T, I]

    var gu_dev = ctx.enqueue_create_buffer[DType.float32](T * I)
    var lay = row_major(T * I)
    comptime sm = silu_mul_kernel[type_of(lay)]
    ctx.enqueue_function[sm](
        TileTensor(g_dev, lay),
        TileTensor(u_dev, lay),
        TileTensor(gu_dev, lay),
        T * I,
        grid_dim=ceildiv(T * I, BLOCK),
        block_dim=BLOCK,
    )

    var out_dev = matmul(ctx, gu_dev, wd_dev, T, I, H)  # [T, H]
    ctx.synchronize()
    return report(dir, max_abs_vs(out_dev, expected))


def main() raises:
    comptime if not has_accelerator():
        raise Error("no GPU accelerator detected — this is a GPU-only build")

    var ctx = DeviceContext()
    var root = "tests/fixtures/kernels/"
    print("kernels spike — GPU vs NumPy reference (tol", TOL, "):")

    var all_ok = True
    # (suffix, kind): kind 0=rmsnorm 1=matmul 2=swiglu
    var names = [
        String("syn_rmsnorm"), String("syn_matmul"), String("syn_swiglu"),
        String("real_rmsnorm"), String("real_matmul"), String("real_swiglu"),
    ]
    for name in names:
        var dir = root + name
        if not exists(dir + "/meta.txt"):
            print("  ", dir, " [skipped — run kernels-capture]", sep="")
            continue
        var ok = (
            run_rmsnorm(ctx, dir) if name.endswith("rmsnorm")
            else run_matmul(ctx, dir) if name.endswith("matmul")
            else run_swiglu(ctx, dir)
        )
        all_ok = all_ok and ok

    if not all_ok:
        raise Error("a GPU kernel does NOT match the reference — spike FAILED")
    print("OK — Mojo Metal matmul / RMSNorm / SwiGLU match the reference")
